config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"

  get "home/about",to: "homes#about" ,as: :homes_about

  resources :books do
    resource :favorites, only:[:create,:destroy]
    resources :comments,only:[:create,:destroy]
  end


  resources :users,only:[:show,:index,:edit,:update] do
    resource :relationships, only:[:create,:destroy]
    get "followings" => "relationships#followings",as:"followings"
    get "followers" => "relationships#followers",as:"followers"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites,dependent: :destroy
  has_many :comments,dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # バリデーションの記述
  validates :title, presence:true
  validates :body, presence:true, length:{maximum:200}

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower,class_name: "User"
  belongs_to :followed,class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,:validatable

  has_many :books,dependent: :destroy
  has_many :favorites,dependent: :destroy
  has_many :comments,dependent: :destroy

# 多対多アソシエーション部分
  has_many :followed,class_name: "Relationship",foreign_key: "followed_id",dependent: :destroy
  has_many :followers,through: :followed,source: :follower

  has_many :follower,class_name: "Relationship",foreign_key: "follower_id",dependent: :destroy
  has_many :followings,through: :follower,source: :followed

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  attachment :profile_image

  validates :name,uniqueness:true,length:{minimum:2,maximum:20}
  validates :introduction,length:{maximum:50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up,keys:[:name])
  # end

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @user=current_user
    @books=Book.all
    @book=Book.new
  end

  def show
    @books=Book.find(params[:id])
    @comment=Comment.new
    @user=@books.user
    @book=Book.new
  end

  def new
    @book=Book.new
  end

  def create
    @book=Book.new(book_params)
    @book.user_id = current_user.id
      if @book.save
        redirect_to book_path(@book.id),notice:"You have created book successfully."
      else
        @user=current_user
        @books=Book.all
        render:index
      end
  end

  def edit
    @book=Book.find(params[:id])
    if @book.user == current_user
      render:edit
    else
      redirect_to books_path
    end
  end

  def update
    @book=Book.find(params[:id])
      if @book.update(book_params)
        redirect_to book_path(@book),notice:"You have updated book successfully."
      else
        render:edit
      end
  end

  def destroy
    book=Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    book=Book.find(params[:book_id])
    comment=current_user.comments.new(comment_params)
    comment.book_id=book.id
    comment.save
    redirect_to request.referer
  end

  def destroy
    Comment.find_by(id:params[:id],book_id:params[:book_id]).destroy
    redirect_to request.referer
  end


  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book=Book.find(params[:book_id])
    favorite=current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book=Book.find(params[:book_id])
    favorite=current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer

  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
  # フォロー機能を作成・保存・削除する
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
  
  # フォロー・フォロワー一覧を表示する
  def followings
    user=User.find(params[:user_id])
    @users=user.followings
  end
  
  def followers
    user=User.find(params[:user_id])
    @users=user.followers
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user=current_user
    @users=User.all
    @book=Book.new
  end

  def show
    @user=User.find(params[:id])
    @books=@user.books
    @book=Book.new
  end



  def edit
    @user=User.find(params[:id])
    if @user == current_user
      render:edit
    else
      redirect_to user_path(current_user)
    end
  end


  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id),notice:"You have updated user successfully."
    else
      render:edit
    end
  end



  private

  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_userinfo.html.erb
      <h2>User info</h2>

      <%= attachment_image_tag user,:profile_image,:fill,100,100, fallback: "no_image.jpg" %>


      <table class="table">
        <tbody>
          <tr>
            <th scope="row">name</th>
            <th>
              <%= user.name %>
            </th>
          </tr>

          <tr>
            <th scope="row">introduction</th>
            <th>
              <%= user.introduction %>
            </th>
          </tr>

          <tr>
            <th>follows</th>
            <th><%= link_to user.followings.count,user_followings_path(user) %></th>
          </tr>

          <tr>
            <th>followers</th>
            <th><%= link_to user.followers.count,user_followers_path(user) %></th>
          </tr>
        </tbody>

      </table>


<!--プロフィール編集欄 or フォローボタン-->
      <div class="row">
        <% if current_user == user %>
          <%= link_to edit_user_path(user) ,class:"btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog "></i>
          <% end %>
        <% else %>
          <% if current_user.following?(user) %>
            <%= link_to "フォロー外す",user_relationships_path(user),method: :delete ,class:"btn btn-danger btn-sm" %>
          <% else %>
            <%= link_to "フォローする",user_relationships_path(user),method: :post,class:"btn btn-success btn-sm" %>
          <% end %>
        <% end %>
      </div>

  <!--New Book 欄-->
    <h2 class="mt-3">New book</h2>

       <%= form_with model:@book, local:true do |f| %>
       <div class="form-group">
        <label for="inputTitle">Title</label>
        <%= f.text_field :title, autofocus: true, id:"inputTitle" ,class:"form-control" %>
      </div>

      <div class="form-group">
        <label for="inputBody">Opinion</label>
        <%= f.text_area :body, autofocus: true, id:"inputTitle" ,class:"form-control" %>
      </div>

      <%= f.submit "Create Book",class:"btn btn-success" %>

      <% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-lg-5 mx-auto">
      <h1>Editing Book</h1>

  <!--バリデーションのエラーメッセージ表示-->
      <% if @book.errors.any? %>
        <div class="text-danger">
          <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%=form_with model:@book,local:true do |f| %>

      <div class="form-group">
        <label for="inputTitle">Title</label>
        <%= f.text_field :title, autofocus: true ,class:"form-control" %>
      </div>

      <div class="form-group">
        <label for="inputBody">Opinion</label>
        <%= f.text_area :body, autofocus: true,class:"form-control" %>
      </div>

      <%= f.submit "Update Book",class:"btn btn-success mb-3" %>

      <% end %>

      <%= link_to "Show",book_path(@book) %> | <%= link_to "Back", books_path %>


    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">

  <!--バリデーションのエラーメッセージ表示-->
  <% if @book.errors.any? %>
    <div class="alert alert-danger">
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">

  <!--indexページの左側-->
    <div class="col-md-3">
      <%= render "books/userinfo",user:@user %>
    </div>



<!--indexページの右側-->

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th scope="col">Title</th>
            <th scope="col">Opinion</th>
            <th></th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <% @books.each do |book| %>

        <tbody>
          <tr>
            <td>
            <!--プロフィール画像リンク-->
            <%= link_to user_path(book.user_id) do %>
              <%= attachment_image_tag book.user,:profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" ,size:"40x40"%>
            <% end %>
            </td>

            <td>
              <%= link_to book.title ,book_path(book.id) %>
            </td>

            <td>
              <%= book.body %>
            </td>

            <td nowrap>
              <% if book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(book),method: :delete,class:"text-danger" do %>
                  <i class="fas fa-heart"></i> <%= book.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(book),method: :post ,class:"text-dark" do %>
                  <i class="far fa-heart"></i> <%= book.favorites.count %>
                <% end %>
              <% end %>
            </td>

            <td nowrap>
              コメント数: <%= book.comments.count %>
            </td>
          </tr>
        </tbody>

        <% end %>

      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-3">
      <%= render "books/userinfo",user:@user %>
    </div>


    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>

      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
               <%= attachment_image_tag @user, :profile_image,:fill,40,40, fallback: "no_image.jpg",size:"40x40" %><br>
               <%= @user.name %>
              <% end %>
            </td>

            <td>
              <%= link_to @books.title,book_path(@books) %>
            </td>

            <td>
              <%= @books.body %>
            </td>

            <td nowrap>
              <% if @books.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(@books),method: :delete,class:"text-danger" do %>
                  <i class="fas fa-heart"></i> <%= @books.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(@books),method: :post ,class:"text-dark" do %>
                  <i class="far fa-heart"></i> <%= @books.favorites.count %>
                <% end %>
              <% end %>
            </td>
            <td nowrap>
              コメント数: <%= @books.comments.count %>
            </td>

          <% if current_user == @user %>
            <td>
              <%= link_to "Edit" ,edit_book_path,class:"btn btn-success btn-sm" %>
            </td>

            <td>
              <%= link_to "Destroy" ,book_path ,method: :delete,class:"btn btn-danger btn-sm" %>
            </td>

          <% end %>
          </tr>
        </tbody>
      </table>

      <h6>コメント一覧</h6>
      <table class="table">
        <tbody>
          <% @books.comments.each do |comment| %>
          <tr>
            <td>
            <%= link_to user_path(comment.user) do %>
               <%= attachment_image_tag comment.user, :profile_image,:fill,40,40, fallback: "no_image.jpg",size:"40x40" %><br>
               <%= comment.user.name %>
            <% end %>
            </td>
            <td>
              <%= comment.comment %>
            </td>
            <% if current_user == comment.user %>
            <td>
              <%= link_to "Destroy", book_comment_path(comment.book,comment),method: :delete,class:"btn btn-danger btn-sm" %>
            </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>

      <div class="form-group">
        <%= form_with(model:[@books,@comment],local:true) do |f| %>
          <%= f.text_area :comment ,class:"form-control" %>
          <%= f.submit "送信" ,class:"btn btn-success mt-3" %>
        <% end %>
      </div>


    </div>

  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>

      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>

    </div>

  </div>

  <div class="btn-wrapper col-5 mx-auto">
    <%= link_to "Log in" ,new_user_session_path ,class:"btn btn-sm btn-block btn-info" %>
    <%= link_to "Sign Up" ,new_user_registration_path ,class:"btn btn-sm btn-block btn-success mt-3" %>
  </div>


</div

app/views/layouts/_flash.html.erb
<!--フラッシュメッセージ-->

<% flash.each do |key,value| %>
  <%= value %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/*******.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg bg-dark">
      <div class="container">
        <%= link_to "Bookers",root_path,class:"navbar-brand text-white" %>

        <div class="navbar-ul">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>

              <li class="nav-item">
                <%= link_to user_path(current_user.id),class:"nav-link text-white" do %>
                  <i class="fas fa-home"></i>
                  Home
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to users_path,class:"nav-link text-white" do %>
                  <i class="fas fa-users"></i>
                  Users
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to books_path,class:"nav-link text-white" do %>
                  <i class="fas fa-book-open"></i>
                  Books
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete,class:"nav-link text-white" do %>
                  <i class="fas fa-sign-out-alt"></i>
                  logout
                <% end %>
              </li>

            <% else %>

              <li class="nav-item">
                <%= link_to root_path,class:"nav-link text-white" do %>
                  <i class="fas fa-home"></i>
                  Home
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to homes_about_path,class:"nav-link text-white" do %>
                  <i class="fas fa-link"></i>
                  About
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to new_user_registration_path,class:"nav-link text-white" do %>
                  <i class="fas fa-user-plus"></i>
                  sign up
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to new_user_session_path,class:"nav-link text-white" do %>
                  <i class="fas fa-sign-in-alt"></i>
                  login
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>

      </div>
      </nav>
    </header>

    <!--フラッシュメッセージ-->
    <p class="notice"><%= render "layouts/flash" %></p>

    <%= yield %>

  </body>

  <footer>
    <div class="container mt-5">
      <p class="text-center">CopyRight Infatop.inc</p>
    </div>
  </footer>

</html>

app/views/relationships/followers.html.erb
<h3>Follow Users</h3>

<% if @users.exists? %>
 <table class="table">
   <thead>
     <tr>
       <th>image</th>
       <th>name</th>
       <th></th>
       <th></th>
       <th></th>
     </tr>
   </thead>
  <% @users.each do |user| %>
   <tbody>
     <tr>
       <td>
         <%= attachment_image_tag user,:profile_image,:fill,40,40,fallback:"no_image.jpg",size:"40x40" %>
       </td>
       <td><%= user.name %></td>
        <td>
          フォロー数: <%= user.followings.count %>
        </td>
        <td>
          フォロワー数: <%= user.followers.count %>
        </td>
        <td>
          <%= link_to "Show",user_path(user) %>
        </td>
     </tr>
   </tbody>
  <% end %>
 </table>
<% else %>
   <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h3>Follower Users</h3>

<% if @users.exists? %>
 <table class="table">
   <thead>
     <tr>
       <th>image</th>
       <th>name</th>
       <th></th>
       <th></th>
       <th></th>
     </tr>
   </thead>
  <% @users.each do |user| %>
   <tbody>
     <tr>
       <td>
         <%= attachment_image_tag user,:profile_image,:fill,40,40,fallback:"no_image.jpg",size:"40x40" %>
       </td>
       <td><%= user.name %></td>
        <td>
          フォロー数: <%= user.followings.count %>
        </td>
        <td>
          フォロワー数: <%= user.followers.count %>
        </td>
        <td>
          <%= link_to "Show",user_path(user) %>
        </td>
     </tr>
   </tbody>
  <% end %>
 </table>
<% else %>
   <p>ユーザーはいません</p>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-5 mx-auto">
      <h2>User info</h2>

 <!--バリデーションのエラーメッセージ表示-->
      <% if @user.errors.any? %>
        <div class="text-danger">
          <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>


      <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <label for="inputName">Name</label>
        <%= f.text_field :name, autofocus: true, id:"inputName" ,class:"form-control" %>
      </div>

      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60 %>
      <div class="form-group">
        <label for="inputImage">Image</label>
        <%= f.attachment_field :profile_image ,class:"form-control-file" %>
      </div>

      <div class="form-group">
        <label for="inputIntroduction">Introduction</label>
        <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction" ,class:"form-control" %>
      </div>

        <%= f.submit "Update User",class:"btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "books/userinfo",user:@user %>
    </div>


    <!--右側内容-->

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>

      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag user,:profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" ,size:"40x40"%>
            </td>

            <td>
              <%= user.name %>
            </td>

            <td>
              フォロー数: <%= user.followings.count %>
            </td>

            <td>
              フォロワー数: <%= user.followers.count %>
            </td>

            <td>
              <% if current_user.following?(user) %>
                <%= link_to "フォロー外す",user_relationships_path(user),method: :delete %>
              <% else %>
                <%= link_to "フォローする",user_relationships_path(user),method: :post %>
              <% end %>
            </td>

            <td>
              <%= link_to "Show",user_path(user) %>
            </td>
          </tr>
        </tbody>

        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-3">
     <%= render "books/userinfo",user:@user %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th scope="col">Title</th>
            <th scope="col">Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <% @books.each do |book| %>

        <tbody>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user,:profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" ,size:"40x40"%>
              <% end %>
            </td>

            <td>
              <%= link_to book.title,book_path(book.id) %>
            </td>

            <td>
              <%= book.body %>
            </td>
          </tr>
        </tbody>
        <% end %>

      </table>

    </div>
  </div>

</div>